# This file was generated by the snapshot workflow in rethab/jira-cli. DO NOT EDIT.
cask "jira-cli-snapshot" do
  version "0.0.1-next.1783862394.15b1ede"

  on_macos do
    on_intel do
      sha256 "b8a08da15553ac2985a80a3feb099682433a188d73d8ef0cbb566c59f6857509"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783862394.15b1ede/jira_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "d1a46f74edb70ad378b8c7e47973bf7562a540d8bbb9c20f7c8454a7a223ad18"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783862394.15b1ede/jira_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_arm64/bin/jira", "bin/jira"
    end
  end

  on_linux do
    on_intel do
      sha256 "3dd63a9f66c894c7e02a58a7657cda8b17e4dce81b1aeed302755fd98a232d21"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783862394.15b1ede/jira_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "c7e7e44839490f72b50871f10b4c27d721b3405f0381fdc63cf79f79a8ee0afa"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783862394.15b1ede/jira_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_arm64/bin/jira", "bin/jira"
    end
  end

  name "jira-cli-snapshot"
  desc "🔥 Feature-rich interactive Jira command-line (snapshot of main)"
  homepage "https://github.com/rethab/jira-cli"

  livecheck do
    skip "Auto-generated on every merge to main."
  end

  conflicts_with cask: "jira-cli"

  binary "bin/jira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/jira"]
    end
  end
  generate_completions_from_executable "bin/jira", "completion",
    shells: [:bash, :zsh, :fish]

  caveats "This is an unstable snapshot build of the main branch."
end
