# This file was generated by the snapshot workflow in rethab/jira-cli. DO NOT EDIT.
cask "jira-cli-snapshot" do
  version "0.0.1-next.1783858004.d685dbf"

  on_macos do
    on_intel do
      sha256 "076b78f4f8aee154dcf5b73a0d2f69125e282aa669c15f4890d8b44eea2018e7"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783858004.d685dbf/jira_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "c1f637d366f1bda8fced98a06633401c2635d79994d661896515483c8ddcd640"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783858004.d685dbf/jira_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_arm64/bin/jira", "bin/jira"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec8978a50ae84fd614ff0e47025c55d3552da28a9fe94159f8c5da8921f4e1ce"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783858004.d685dbf/jira_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "e5f818dc1970aac830ad3ea42dab390cc3930406a667ceb85d06141dd301567f"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783858004.d685dbf/jira_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_arm64/bin/jira", "bin/jira"
    end
  end

  name "jira-cli-snapshot"
  desc "🔥 Feature-rich interactive Jira command-line (snapshot of main)"
  homepage "https://github.com/rethab/jira-cli"

  livecheck do
    skip "Auto-generated on every merge to main."
  end

  conflicts_with cask: "jira-cli"

  binary "bin/jira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/jira"]
    end
  end
  generate_completions_from_executable "bin/jira", "completion",
    shells: [:bash, :zsh, :fish]

  caveats "This is an unstable snapshot build of the main branch."
end
