# This file was generated by the snapshot workflow in rethab/jira-cli. DO NOT EDIT.
cask "jira-cli-snapshot" do
  version "0.0.1-next.1783832678.5096397"

  on_macos do
    on_intel do
      sha256 "b5c9922682571b71aa6b039e33bc058298f85025434d4d0bb6119dc949508d3e"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783832678.5096397/jira_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "68ba73b6099c90346db79175f30cb6430c6a44c1f4378814791cf9375ca049c2"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783832678.5096397/jira_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_arm64/bin/jira", "bin/jira"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc81712338825ce2089794b5d8021e71dc63b6a19b1440d44cf140d17ae316a4"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783832678.5096397/jira_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "108c13b117425e8dc0f603abdae34e6e41731e4eb433843b5822b338592c9673"
      url "https://github.com/rethab/jira-cli/releases/download/snapshot-0.0.1-next.1783832678.5096397/jira_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_arm64/bin/jira", "bin/jira"
    end
  end

  name "jira-cli-snapshot"
  desc "🔥 Feature-rich interactive Jira command-line (snapshot of main)"
  homepage "https://github.com/rethab/jira-cli"

  livecheck do
    skip "Auto-generated on every merge to main."
  end

  conflicts_with cask: "jira-cli"

  binary "bin/jira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/jira"]
    end
  end
  generate_completions_from_executable "bin/jira", "completion",
    shells: [:bash, :zsh, :fish]

  caveats "This is an unstable snapshot build of the main branch."
end
